geo2france/odema-viz

.eslintrc.cjs, .gitignore, index.html, package-lock.json, package.json, src/App.tsx, src/components/Header/Header.tsx, src/components/Header/header.css, src/components/TableTabulator/TableTabulator.tsx, src/context/IndicatorsContext.tsx, src/context/ThemeContext.tsx, src/main.tsx, src/models/Indicator.ts, src/models/geo2france.types.ts, src/models/indicator.types.ts, src/models/matrice.types.ts, src/services/geoweb.service.ts, src/views/Dashboard.tsx, src/views/TechnicalSheet.tsx, src/vite-env.d.ts, tsconfig.json, tsconfig.node.json, vite.config.ts
[ODEMADREAL-104] Display indicator name technical sheet
=> [ODEMADREAL-104] Display indicator name technical sheet

src/components/SelectWithBoxes/SelectWithBoxes.tsx, src/views/TechnicalSheet.tsx
[ODEMADREAL-113] add waste types selector with options
=> [ODEMADREAL-113] add waste types selector with options

src/components/SelectWithBoxes/SelectWithBoxes.tsx, src/helpers/formatters.helper.ts, src/helpers/urlParams.helper.ts, src/views/TechnicalSheet.tsx
[ODEMADREAL-114] associate waste types selection on url and cookie
=> [ODEMADREAL-114] associate waste types selection on url and cookie

src/components/SelectMultiple/SelectMultiple.tsx, src/components/SliderRange/SliderRange.tsx, src/helpers/formatters.helper.ts, src/models/matrice.types.ts, src/models/selectors.types.ts, src/views/TechnicalSheet.tsx
[ODEMADREAL-117] slider year range
=> [ODEMADREAL-117] slider year range

src/views/TechnicalSheet.tsx
[ODEMADREAL-113] change as analyse axis selector
=> [ODEMADREAL-113] change as analyse axis selector

src/components/RadioGroupUnit/RadioGroupUnit.tsx, src/models/matrice.types.ts, src/views/TechnicalSheet.tsx
[ODEMADREAL-138] display unit selection
=> [ODEMADREAL-138] display unit selection

src/helpers/formatters.helper.ts, src/helpers/urlParams.helper.ts, src/views/TechnicalSheet.tsx
[ODEMADREAL-143] Handle cookie and URL for unit selection
=> [ODEMADREAL-143] Handle cookie and URL for unit selection

src/views/TechnicalSheet/TechnicalSheet.tsx
[NO-JIRA] temporary deactivate cookie tracking
=> [NO-JIRA] temporary deactivate cookie tracking

src/App.tsx
[DREALODEMA-147] define statically basename of application routing
=> [DREALODEMA-147] define statically basename of application routing

src/components/TableTabulator/TableTabulator.tsx, src/models/matrice.types.ts, src/views/TechnicalSheet/TechnicalSheet.tsx, vite.config.ts
[DREALODEMA-123] Display table values with filter
=> [DREALODEMA-123] Display table values with filter

src/components/SelectWithBoxes/SelectWithBoxes.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-148] disable selector when no axis is available
=> [DREALODEMA-148] disable selector when no axis is available

src/components/SelectWithBoxes/SelectWithBoxes.tsx, src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-148] display table with sum and average
=> [DREALODEMA-148] display table with sum and average

vite.config.ts
[DREALODEMA-147] vite config binded to basename
=> [DREALODEMA-147] vite config binded to basename

src/views/TechnicalSheet/TechnicalSheet.tsx, vite.config.ts
[DREALODEMA-147] handle displaying table
=> [DREALODEMA-147] handle displaying table 

src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-147] temporary deactivate columns sort
=> [DREALODEMA-147] temporary deactivate columns sort

src/components/TableTabulator/TableTabulator.tsx, src/helpers/formatters.helper.ts, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-128] share data between table and graphs in coming
=> [DREALODEMA-128] share data between table and graphs in coming

src/components/PieChart/PieChart.tsx, src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
=> [DREALODEMA-129] Pie chart

src/components/StackLineChart/StackLineChart.tsx, src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-146] reduce columns from yearRange and set correct label for territories
=> [DREALODEMA-146] reduce columns from yearRange and set correct label for territories

src/components/Tabs/Tabs.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-129] disable pie chart when no axis
=> [DREALODEMA-129] disable pie chart when no axis

src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-146] fixing an error on set unit
=> [DREALODEMA-146] fixing an error on set unit

src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-125] fixing sum and average only for EPCI on table
=> [DREALODEMA-125] fixing sum and average only for EPCI on table

src/components/TableTabulator/TableTabulator.tsx, src/helpers/formatters.helper.ts, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-125] Conditionnal rendering sum and average from EPCI
=> [DREALODEMA-125] Conditionnal rendering sum and average from EPCI

src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-154] Priority to get url params until using cookie data for territories
=> [DREALODEMA-154] Priority to get url params until using cookie data for territories

src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-154] fixing handling empty cookie territory
=> [DREALODEMA-154] fixing handling empty cookie territory

src/helpers/urlParams.helper.ts, src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-173] selected all axis when no parameters in URL
=> [DREALODEMA-173] selected all axis when no parameters in URL

src/components/StackLineChart/StackLineChart.tsx
[DREALODEMA-168] scrolling legend when important
=> [DREALODEMA-168] scrolling legend when important

src/views/TechnicalSheet/TechnicalSheet.tsx
[DREALODEMA-153] fixing no unit per inhabitants with basic unit
=> [DREALODEMA-153] fixing no unit per inhabitants with basic unit

src/components/TableTabulator/TableTabulator.tsx
[DREALODEMA-177] separate thousands with a space
=> [DREALODEMA-177] separate thousands with a space

.gitignore, index.html, src/App.tsx, src/components/TextField/TextField.tsx, src/helpers/urlParams.helper.ts, src/views/TechnicalSheet/TechnicalSheet.tsx, vite.config.ts
[NO-JIRA-HASHROUTING] change as hashrouter mode and fixing impacts
=> [NO-JIRA-HASHROUTING] change as hashrouter mode and fixing impacts

src/components/StackLineChart/StackLineChart.tsx
[DREALODEMA-181] display values of 0 on graphics
=> [DREALODEMA-181] display values of 0 on graphics

vite.config.ts
[DREALODEMA-182] configuring chunkSizeWarningLimit
=> [DREALODEMA-182] configuring chunkSizeWarningLimit

src/components/ShareButton/ShareButton.tsx, src/components/ShareButton/sharebutton.css, src/components/StackLineChart/StackLineChart.tsx, src/components/TableTabulator/TableTabulator.tsx, src/views/TechnicalSheet/TechnicalSheet.tsx
Évolutions :
Ajout d'un bouton permettant de copier le lien de partage
Possibilité de switcher entre 3 types de graphiques (Lignes, barres et barres empilées)
Cacher le donut si pas d'axe
Empiler les barres par type de territoire (Région, Département ou EPCI)
=> Reprise dev SIGAC

package.json, src/components/Header/Header.tsx
Fix #58  pour le lien vers la page d'accueil qui renvoyait à la racine du serveur au lieu de la racine de l'application
=> fix home button link
